[build]
  publish = "out"
  command = "npm run build"

# 404 fallback for static export
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
