// Re-export from auto-generated config for backwards compatibility
export {
  categories,
  getCategoryById,
  getAlbumById,
} from './gallery-config-auto';

export type {
  CategoryConfig,
  AlbumConfig,
  GalleryImage,
} from './gallery-config-auto';

import { categories, getCategoryById } from './gallery-config-auto';

// Helper functions for backwards compatibility with existing pages

/**
 * Get image paths for a specific gallery/album
 * Maps from album ID like 'aerospace/starbase' to array of image src paths
 */
export function getGalleryImagePaths(albumId: string): string[] {
  // Try to find album by ID directly
  for (const cat of Object.values(categories)) {
    const album = (cat as any).albums.find((a: any) => a.id === albumId);
    if (album) {
      return album.images.map((img: any) => img.src);
    }
  }
  
  // Handle legacy mappings - these map from the IDs used in page files
  // to the album IDs generated by build-gallery.js (category/album-slug format)
  const legacyMappings: Record<string, string> = {
    // Aerospace page uses these IDs
    'aerospace-starbase-film': 'aerospace/starbase-film',
    'aerospace/astronauts-charlie-duke': 'aerospace/charlie-duke',
    'aerospace/astronauts-fred-haise': 'aerospace/fred-haise',
    // Weddings page
    'weddings-lauren-2024': 'weddings/lauren-elphin',
    // Portraits page  
    'portraits-hillary-astrid': 'portraits/hillary-astrid',
    'portraits-blackbeltbbj': 'portraits/blackbeltbbj',
    // Landscapes page
    'landscapes-american-landscapes': 'landscapes/american-landscapes',
    'landscapes-big-bend-film': 'landscapes/big-bend-film',
    'landscapes-costa-rica': 'landscapes/costa-rica',
    // Abstract page
    'abstract-from-above': 'abstract/from-above',
  };
  
  const mappedId = legacyMappings[albumId] || albumId;
  
  for (const cat of Object.values(categories)) {
    const album = (cat as any).albums.find((a: any) => a.id === mappedId);
    if (album) {
      return album.images.map((img: any) => img.src);
    }
  }
  
  return [];
}

/**
 * Get the first image from a gallery/album
 */
export function getFirstImage(albumId: string): string | undefined {
  const images = getGalleryImagePaths(albumId);
  return images[0];
}

/**
 * Get all gallery IDs
 */
export function getAllGalleryIds(): string[] {
  const ids: string[] = [];
  
  for (const cat of Object.values(categories)) {
    for (const album of (cat as any).albums) {
      ids.push(album.id);
    }
  }
  
  return ids;
}

/**
 * Get gallery IDs for a specific category
 */
export function getCategoryGalleryIds(categoryId: string): string[] {
  const category = getCategoryById(categoryId);
  
  if (!category) return [];
  return category.albums.map(a => a.id);
}

// Legacy type aliases for backwards compatibility
export type GalleryConfig = import('./gallery-config-auto').CategoryConfig;
export type GalleryCategory = import('./gallery-config-auto').CategoryConfig;

// Backwards compatibility exports (empty arrays for old code that imported these)
export const weddingAlbums: any[] = [];
export const aerospaceGalleries: any[] = [];
export const landscapeAlbums: any[] = [];
export const eventGalleries: any[] = [];
export const portraitGalleries: any[] = [];
export const abstractGalleries: any[] = [];

// Export legacy image helpers that pages use
export const weddingHeroImage = getFirstImage('weddings/catskills-wedding') || '';
export const homeHeroImage = getFirstImage('weddings/lauren-elphin') || getFirstImage('weddings/catskills-wedding') || '';
export const homeAboutImage = getFirstImage('portraits/hillary-astrid') || '';

// Home page category cards
export const homeCategoryCards = [
  { 
    title: 'Weddings', 
    link: '/weddings', 
    icon: 'Camera',
    image: getFirstImage('weddings/lauren-elphin') || getFirstImage('weddings/catskills-wedding') || '',
    description: 'Capturing your forever with timeless elegance'
  },
  { 
    title: 'Aerospace', 
    link: '/aerospace', 
    icon: 'Rocket',
    image: getFirstImage('aerospace/starbase') || '',
    description: 'Documenting the new space age'
  },
  { 
    title: 'Events', 
    link: '/events', 
    icon: 'Music',
    image: getFirstImage('events/beach-house-concert') || '',
    description: 'Capturing the energy of special occasions'
  },
  { 
    title: 'Landscapes', 
    link: '/landscapes', 
    icon: 'Mountain',
    image: getFirstImage('landscapes/american-landscapes') || '',
    description: 'From dramatic vistas to intimate scenes'
  },
];

// Portraits page helpers
export const portraitsHillaryAstridImages = getGalleryImagePaths('portraits/hillary-astrid');
export const portraitsBlackbeltImages = getGalleryImagePaths('portraits/blackbeltbbj');
export const portraitsHeroImage = getFirstImage('portraits/hillary-astrid') || '';

// Landscapes page helpers  
export const landscapesAmericanLandscapesImages = getGalleryImagePaths('landscapes/american-landscapes');
export const landscapesCostaRicaImages = getGalleryImagePaths('landscapes/costa-rica');

// Events page helpers
export const eventsBeachHouseImages = getGalleryImagePaths('events/beach-house-concert');
export const eventsFireDancerImages = getGalleryImagePaths('events/fire-dancer');

// Abstract page helpers
export const abstractFromAboveImages = getGalleryImagePaths('abstract/from-above');
